### ISSUE TITLE
Version 0.5.0?

### ISSUE THREAD

**Issue by mroach** [square/ruby-rrule#52]
Back in March I got a dependency update notification for v0.5.0 since [it's on Rubygems](https://rubygems.org/gems/rrule/versions/0.5.0). There's no 0.5.0 in the Changelog though. I see a [tag v0.5.0](https://github.com/square/ruby-rrule/commits/v0.5.0) though.

Is v0.5.0 intended as a normal release? I currently have this upgrade held back since on my side for lack of a changelog entry and viewable diff. It's not causing an issue, I just wanted to get clarity on this. Thanks :)

**Comment by rmitchell-sq** [comment]
Hi @mroach! Sorry for the delay - I'm pretty sure I just forgot to add an entry to the changelog here 🤦 I'll add an entry there to hopefully clear up the confusion.
